# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build and run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_muscl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build: [Release, RelWithDebInfo, Debug]
        riemann: [EXACT, HLLC]
        precision: [SINGLE, DOUBLE]
        limiter: [MINMOD, VANLEER]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure CMake 
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build}} -DSOLVER=GODUNOV -DRIEMANN=${{matrix.riemann}} -DPRECISION=${{matrix.precision}} -DLIMITER=${{matrix.limiter}}

    - name: Build 
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build


